name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install

      - name: Build and release Windows x64
        if: matrix.os == 'windows-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_RELEASE }}
        run: npm run build:winx64

      - name: Build and release Windows ia32
        if: matrix.os == 'windows-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_RELEASE }}
        run: npm run build:winia32

      - name: Build and release macOS Intel
        if: matrix.os == 'macos-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_RELEASE }}
        run: npm run build:intel

      - name: Build and release macOS ARM
        if: matrix.os == 'macos-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_RELEASE }}
        run: npm run build:arm

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-builds
          files: |
            release/**/*.exe
            release/**/*.dmg
            release/**/*.snap
          if-no-files-found: error