name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*' # 匹配 v0.0.1, v1.2.3 等等的 tag

  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [win32, linux, mac]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build for ${{ matrix.platform }}
        run: |
          npm run build -- --${{ matrix.platform }}

      - name: Archive build files
        run: |
          mkdir -p release
          mv dist/* release/
        if: always()

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: electron-app-${{ matrix.platform }}
          path: release/
          retention-days: 7

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: electron-app-win32
          path: release/win32

      - uses: actions/download-artifact@v3
        with:
          name: electron-app-linux
          path: release/linux

      - uses: actions/download-artifact@v3
        with:
          name: electron-app-mac
          path: release/mac

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }} # 使用推送的标签作为 release 的 tag
          name: Release ${{ github.ref }} # Release 名称与 tag 名一致
          body: |
            发布版本 ${{ github.ref }}，包含以下产物：
            - Windows 打包文件
            - macOS 打包文件
            - Linux 打包文件
          files: |
            release/win32/*
            release/linux/*
            release/mac/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_RELEASE }}

