name: Release Electron App

on:
  workflow_run:
    workflows: ["Build Electron App"]
    types:
      - completed

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_RELEASE }}

      - name: Upload Release Assets
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.run_number }}
          files: |
            release/**/*.exe
            release/**/*.dmg
            release/**/*.AppImage
            release/**/*.snap
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_RELEASE }}
